# Generated by Django 3.1.5 on 2021-10-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211012_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
