# Generated by Django 3.1.5 on 2021-10-12 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211012_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
