# Generated by Django 3.1.5 on 2021-10-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'todo', 'verbose_name_plural': 'todo'},
        ),
    ]
